backend:
  name: git-gateway
media_folder: "static/img"
public_folder: "/img"
collections:
  - name: lp
    label: Landing Page
    folder: lp
    create: true
    fields:
      # We'll put all the variable pieces of the landing page here.
      - { name: slug, label: Slug }
      - { name: body, label: Body, widget: markdown }